### ISSUE TITLE
Release new version and update dependency in pdfkit

### ISSUE THREAD

**Issue by Nabeelhassan** [foliojs/linebreak#24]
Hello,

Please publish a new version of linebreak and update its dependency for pdfkit.

[https://github.com/foliojs/unicode-trie/issues/9](url)

**Comment by liborm85** [comment]
@devongovett Please can you release a new version?

**Comment by cinan** [comment]
please, release a new version

**Comment by liborm85** [comment]
Because there probably won't be an official release, I made fork [foliojs-fork/linebreak](https://github.com/foliojs-fork/linebreak) with lastest changes from github master and publish on npm [@foliojs-fork/linebreak](https://www.npmjs.com/package/@foliojs-fork/linebreak). Will be gradually updated according to changes here.

**Comment by ksze** [comment]
@liborm85 There hasn't been a new official release in a long time. What's going on with the project?

**Comment by liborm85** [comment]
There is no new official version, because I don't have permissions to release this project on npm.

**Comment by ksze** [comment]
> There is no new official version, because I don't have permissions to release this project on npm.

What happened to the person who has permission?

**Comment by liborm85** [comment]
Is inactive...

**Comment by devongovett** [comment]
New version has been released.
