### ISSUE TITLE
library not working properly for emoji

### ISSUE THREAD

**Issue by terence410** [foliojs/linebreak#31]
There are mainly two issues:

- not all emoji behave the same, for example, 🤑 has a different line break checking with 😀
- 8 bytes emoji 👨🏿‍🦱 are treated as two characters.

**Comment by liborm85** [comment]
Released version on npm [linebreak](https://www.npmjs.com/package/linebreak) support only Unicode 7.

Support for Unicode 12 (which can also emoji) is available only on github master. Release on npm is problematic because https://github.com/foliojs/linebreak/issues/24. But I made fork [foliojs-fork/linebreak](https://github.com/foliojs-fork/linebreak) with support Unicode 12 and publish on npm [@foliojs-fork/linebreak](https://www.npmjs.com/package/@foliojs-fork/linebreak). You can try it.
