### ISSUE TITLE
Wrong text wrapping

### ISSUE THREAD

**Issue by liborm85** [foliojs/linebreak#7]
Texts with dashes are wrapped incorrectly. Tested on uuid strings.

**Example 1:**

Source text:
`67e404e5-d4fb-2732-be14-2f60cf8b3cc2`

Actual result:
`67e404e5-`
`d4fb-2732-`
`be14-2f60cf8b3cc2`

Expected result:
`67e404e5-`
`d4fb-`
`2732-`
`be14-`
`2f60cf8b3cc2`

**Example 2:**

Source text:
`9847b959-135a-7014-3ad5-5223f4d2eaf5`

Actual result:
`9847b959-135a-7014-3ad5-5223f4d2eaf5`

Expected result:
`9847b959-`
`135a-`
`7014-`
`3ad5-`
`5223f4d2eaf5`

Please, could it be fixed?

**Comment by devongovett** [comment]
This is actually correct behavior according to Unicode. The difference in your first example between the first hyphen where it does break, and the second hyphen when it does not is that the character after the second hyphen is a number rather than a letter. This is to distinguish between usage of the hyphen as a minus sign, in which case it should not break. See http://www.unicode.org/reports/tr14/#HY.

You can manually add a zero width space character (`\u200B`) after the hyphen to provide a break opportunity there.

**Comment by devongovett** [comment]
Alternatively, use the explicit hyphen character (`\u2010`) instead of the hyphen-minus character (`\u002d`). That will also allow breaks.
